[package]
name = "poly-bot"
version = "0.1.0"
authors = ["Alexandra Ã˜stermark <alex.cramt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6"
tokio = { version = "1.1", features = ["full"] }
once_cell = "1.5.2"
regex = "1.4.3"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.61"
tokio-postgres = "0.7.0"
async-trait = "0.1.42"
tokio-test = "0.4.0"
eyre = "0.6.5"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.10.2"
