[package]
name = "poly-bot"
version = "0.1.0"
authors = ["Alexandra Ã˜stermark <alex.cramt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.6"
tokio = { version = "1.1", features = ["full"] }
once_cell = "1.5.2"
regex = "1.4.3"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.61"
